# Generated by Django 2.2.2 on 2019-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
