# Generated by Django 2.2.2 on 2019-06-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190604_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saloon',
            old_name='ad_seond',
            new_name='ad_second',
        ),
    ]
