# Generated by Django 2.2.2 on 2019-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190604_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
