# Generated by Django 2.2.2 on 2019-07-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserSaloon',
        ),
    ]
