# Generated by Django 2.2.2 on 2019-07-14 03:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190714_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 7, 14, 3, 9, 33, 871995))),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saloon_subscribe', to='register.Saloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscribe', to='register.UserSaloon')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('type_post', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('description', models.TextField(blank=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saloon_post', to='register.Saloon')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 7, 14, 3, 9, 33, 870446))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_like', to='register.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_like', to='register.UserSaloon')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 7, 14, 3, 9, 33, 871209))),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_comment', to='register.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comment', to='register.UserSaloon')),
            ],
        ),
    ]
