# Generated by Django 2.2.2 on 2019-07-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20190714_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='saloon',
            name='pincode',
            field=models.CharField(max_length=250),
        ),
    ]
